apiVersion: v1
kind: Service
metadata:
  name: api-orders-service
  labels:
    run: api-orders-service
spec:
  selector:
    app: api-orders-pod
  ports:
  - name: port8080  
    port: 8080    
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer