name: sonarqube

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  sonar-analysis:
    name: Analyze SnackTech
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Tools
      run: dotnet tool restore  # Use dotnet tool restore

    - name: Run Tests and Generate Coverage Report
      run: |
        dotnet build ./SnackTech.Orders.sln
        dotnet test ./SnackTech.Orders.sln --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=TestResults.trx"
        reportgenerator -reports:TestResults.trx -targetdir:./Coverage -reporttypes:OpenCover
        ls -lR Coverage  # Debug: List directory contents

    - name: Run SonarScanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        BRANCH_NAME: ${{ github.ref_name }}
      run: |
        dotnet-sonarscanner begin /k:"SnackTechTeam_snacktech-api-orders" /o:"snacktechteam" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths="./Coverage/coverage.opencover.xml" /d:sonar.cs.vstest.reportsPaths="TestResults.trx" /d:sonar.branch.name="${{ env.BRANCH_NAME }}"
        dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"